### PR TITLE
Stage 1

### PR DESCRIPTION
**Pull request by Sahar321**
implement the backend api for News explorer app

### CODE REVIEW

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [x] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  TThe following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
       _In the dev mode it is impossible to log in because of the incorrect import of the secret key. It's name must be corrected: `const { developmentJwtSecret } = require('../constant/constant');`_
  - [x] `GET returns` data saved by the user.
       _In order to get the data saved by the user you need to filter data by the `owner` field, for example, https://snipboard.io/U6XVJs.jpg_
  - [x] `POST` creates a data item with the data passed inside the request body.
  - [x] `DELETE` deletes the saved data item using `_id`.
- [x]  Users can't delete saved data from other user profiles
      _It is possible to delete data from other user profiles because the method findByidAndRemove will remove the data anyways despite the error. In order to prevent the deletion, you need to find the article first (use findById), then check the owner, and then delete it (you can use .remove()), for example, https://snipboard.io/c8jlXd.jpg_
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
    _Not found route also should be protected with authorization_
- [x]  User routes and data-related routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
       - _In the auth middleware in case of an invalid token it is necessary to return the error with the 401 code, not 400_
       - _The `not Found` route should throw an error class with the 404 code, but instead, it returns the successful 200 code_
       - _In the `deleteArticleById` function you need to use the 404 error in the `orFail` method instead of 403_
       - _You need to add "ValidationError" handling when creating a user or an article, for example https://snipboard.io/SmnuAa.jpg_
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [ ]  Validation implemented correctly:
  - [ ] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
      - _Celebrate's `uri()` method will pass the URLs without domain (https://incorrect), so instead to check URLs you can use regular expression or validator's `isURL` method _
      - _`unknown(true)` option allows passing unknown fields that are not described in the schema. You should not use this method in the project_
  - [x] Data is validated before being added to the database.
      _In the article scheme the `owner` field shouldn't be omitted, this field can be returned with other data because it will help to find the data saved by the user. So you need to delete the `select: false` option_
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
  - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
     _error logger must be placed right before the error handlers and after all the routes: https://snipboard.io/bl5kPm.jpg_
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [ ] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [x]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 51

## Additional comments:
- When getting the saved articles by the user the .orFail() method can be deleted because if the user didn't save the articles he will get the empty array instead of the 404 error

**Comment by Sahar321** [comment]
1. **The not Found route should throw an error class with the 404 code, but instead, it returns the successful 200 code** 
i didnt find that, can you show me where your saw please?

2.**You need to add "ValidationError" handling when creating a user or an article, for example** i made it already:
router.delete('/articles/:articleId', article.articleId, deleteArticleById);
thank you very much : )

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [x] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  TThe following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET returns` data saved by the user.
  - [x] `POST` creates a data item with the data passed inside the request body.
  - [x] `DELETE` deletes the saved data item using `_id`.
- [x]  Users can't delete saved data from other user profiles
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and data-related routes are described in separate files.
- [ ]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
       - _The `not Found` route should throw an error class with the 404 code, but instead, it returns the successful 200 code: https://snipboard.io/u0HA48.jpg. An example of a correct implementation is https://snipboard.io/G63aeb.jpg_
       - _I apologize for not pointing out this error in the first review. In the `registerNewUser` controller, the 409 error is sent by default. But in order to submit this error, it must be checked for error code 11000 (which the database throws when trying to add a duplicate), for example, https://snipboard.io/BpsaEY.jpg_
       - _Besides the `celebrate` validation, when creating a user or an article in the controllers you also need to add "ValidationError" (in catch block) handling. Here is an example of the implementation in the `registerNewUser` controller, https://snipboard.io/BpsaEY.jpg._
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [ ]  Validation implemented correctly:
  - [ ] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
      - _Celebrate's `uri()` method will pass the URLs without domain (https://incorrect), so instead to check URLs you can use regular expression or validator's `isURL` method_
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
  - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [ ] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
     _This point would have been counted if error messages are also moved to constants_
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 84

## Additional comments:
- When getting the saved articles by the user the .orFail() method can be deleted because if the user didn't save the articles he will get the empty array instead of the 404 error
- You can also specify the required id length when validating it: `articleId: Joi.string().hex().required().length(24)`

**Comment by adzhenalieva** [comment]
> 1. **The not Found route should throw an error class with the 404 code, but instead, it returns the successful 200 code**
>    i didnt find that, can you show me where your saw please?
> 
> 2.**You need to add "ValidationError" handling when creating a user or an article, for example** i made it already: router.delete('/articles/:articleId', article.articleId, deleteArticleById); thank you very much : )

Thank you for your questions. The answers are added in the `API errors are handled` with the examples.

**Pull request merged**
